#!/bin/sh

HWaddr=$(ifconfig | grep $(uci get network.wan.device) | awk '{print $5}')
info=$(ifconfig awg0 | grep "RX bytes")
RX=$(echo $info | awk '{print $2}' | awk -F: '{print $2}')
TX=$(echo $info | awk '{print $6}' | awk -F: '{print $2}')
if curl -s -m 5 --interface awg0 ifconfig.co > /dev/null; then
    ST="UP"
else
    ST="DOWN"
fi

count=0
while true; do
    if curl -m 3 -o /dev/null -s dweet.io; then
        echo "HWaddr=$HWaddr"
        echo "awg0 $ST Rx/Tx=$RX/$TX bytes"
        curl -o /dev/null -s dweet.io/dweet/for/$HWaddr?"RX=$RX&TX=$TX&State=$ST"
        break
    else
        echo "dweet.io is not available. Check the internet availability [$count]"
        count=$((count+1))
    fi
done

